# Site settings
title: Han Zhang
description: Han Zhang website
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Han Zhang
user_description: PhD candidate from uOttawa graduating in August 2025. 4+ year of experience. Seeking for AI research/MLE positions.
user_title: Ph.D. in AI | Large language models | Reinforcement learning | Distributed systems
email: hzhan363@uottawa.ca
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
# linkedin_username: murraco
# github_username:  murraco
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

